version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: pmsproject_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "127.0.0.1:5432:5432"


  redis:
    image: redis:6-alpine
    ports:
      - "127.0.0.1:6379:6379"
